---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Installing Linux Apps
      become: true
      dnf:
        name: "{{ item }}"
        install_recommends: yes
        state: latest
      loop:
        - python-pip
        - virtualbox
        - vagrant
        - terraform

    - block:
        - name: Installing Kubectl 1.22.0
          become: true
          get_url:
            url: "https://dl.k8s.io/release/v1.22.0/bin/linux/amd64/kubectl"
            dest: /usr/local/bin/kubectl
            mode: 755
        - name: Downloading Kubectx and Kubens
          become: true
          git:
            repo: "https://github.com/ahmetb/kubectx"
            dest: /opt/kubectx
        - name: Creating Symlink to kubectx and kubens
          become: true
          file:
            src: "/opt/kubectx/{{ item }}"
            dest: "/usr/local/bin/{{ item }}"
            state: link
          with_items:
            - kubectx
            - kubens
        - name: Creating ZSH Completion
          file:
            src: "/opt/kubectx/completion/{{ item }}"
            dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/completions/_{{ item }}"
            state: link
          with_items:
            - kubectx.zsh
            - kubens.zsh

    - block:
        - name: Adding Longsleep/Golang Backports Repository
          become: true
          apt_repository:
            repo: "ppa:longsleep/golang-backports"
        - name: Install Golang
          become: true
          apt:
            name: golang-go

    # OPTIONAL:
    #  - PEEK - Lightweight Screen Recorder that can export as GIF
    #  - OBS-STUDIO - Screen Recorder and Casting Software
    #  - Brave Browser - Secure web browser
    #  - Ulauncher - Application Launcher

    - block:
        - name: Adding Peek Repository
          become: true
          apt_repository:
            repo: "ppa:peek-developers/stable"
        - name: Install Peek
          become: true
          apt:
            name: peek

    - block:
        - name: Install obsproject Ubuntu Repo
          become: true
          apt_repository:
            repo: "ppa:obsproject/obs-studio"
        - name: Install obs Studio
          become: true
          apt:
            name: obs-studio

    - block:
        - name: Install Brave Key
          become: true
          apt_key:
            url: "https://brave-browser-apt-release.s3.brave.com/brave-core.asc"
            state: present
        - name: Install Brave Repository
          become: true
          apt_repository:
            repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
            state: present
            filename: brave
        - name: Install Brave Browser
          become: true
          apt:
            name: brave-browser

    - block:
        - name: Adding Ulauncher Repository
          become: true
          apt_repository:
            repo: "ppa:agornostal/ulauncher"
        - name: Install Ulauncher
          become: true
          apt:
            name: ulauncher
