---
# tasks file for install_docker

- name: make sure dnf-plugins.core installed
  dnf:
    name: dnf-plugins-core
    state: present

- import_tasks: installPackages.yml
- import_tasks: addRepo.yml
- import_tasks: installDocker.yml
- import_tasks: addUser.yml
